# Generated by Django 3.0.3 on 2020-02-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_researchscholar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('details', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('COM', 'communicated'), ('REJ', 'rejected'), ('ACT', 'accepted')], max_length=3)),
                ('pub_type', models.CharField(choices=[('CNF', 'conference'), ('JRN', 'journal')], max_length=3)),
                ('pub_date', models.DateField(blank=True, null=True)),
                ('doi_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Digital Object Indentifier Number')),
                ('page_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('faculty_authors', models.ManyToManyField(blank=True, related_name='publications', to='users.Faculty')),
                ('scholar_authors', models.ManyToManyField(blank=True, related_name='publications', to='users.ResearchScholar')),
                ('student_authors', models.ManyToManyField(blank=True, related_name='publications', to='users.Student')),
            ],
            options={
                'verbose_name': 'publication',
                'ordering': ['-pub_date'],
                'default_related_name': 'publications',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('details', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('COM', 'communicated'), ('REJ', 'rejected'), ('ACT', 'accepted')], max_length=3)),
                ('agency', models.CharField(max_length=100)),
                ('scheme', models.CharField(max_length=50)),
                ('pi_copi', models.CharField(max_length=100, verbose_name='Principal Investigator/Co-Principal Investigator')),
                ('np_form', models.ImageField(blank=True, null=True, upload_to='', verbose_name='NP Form')),
                ('send_date', models.DateField(blank=True, null=True, verbose_name='date of sending')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('faculty_authors', models.ManyToManyField(blank=True, related_name='projects', to='users.Faculty')),
                ('proposed_by', models.ManyToManyField(related_name='proposed_projects', to='users.Faculty')),
                ('scholar_authors', models.ManyToManyField(blank=True, related_name='projects', to='users.ResearchScholar')),
                ('student_authors', models.ManyToManyField(blank=True, related_name='projects', to='users.Student')),
            ],
            options={
                'verbose_name': 'project',
                'ordering': ['-send_date', '-start_date'],
                'default_related_name': 'projects',
            },
        ),
    ]
