# Generated by Django 2.2.6 on 2019-10-28 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_department_faculty_student'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('COM', 'communicated'), ('REJ', 'rejected'), ('ACT', 'accepted')], max_length=3)),
                ('pub_type', models.CharField(choices=[('CNF', 'conference'), ('JRN', 'journal')], max_length=3)),
                ('pub_date', models.DateField(blank=True, null=True)),
                ('doi_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Digital Object Indentifier Number')),
                ('page_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('author', models.ManyToManyField(related_name='publications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'publication',
                'ordering': ['-pub_date'],
                'default_related_name': 'publications',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('pi_copi', models.CharField(max_length=100, verbose_name='Principal Investigator/Co-Principal Investigator')),
                ('send_date', models.DateField(blank=True, null=True, verbose_name='date of sending')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('author', models.ManyToManyField(related_name='projects', to='research.ResearchScholar')),
                ('proposed_by', models.ManyToManyField(related_name='projects', to='users.Faculty')),
            ],
            options={
                'verbose_name': 'project',
                'ordering': ['-send_date', '-start_date'],
                'default_related_name': 'projects',
            },
        ),
    ]
