# Generated by Django 3.0.2 on 2020-01-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_auto_20191103_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='np_form',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='NP Form'),
        ),
        migrations.AddField(
            model_name='project',
            name='scheme',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchscholar',
            name='co_supervisor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchscholar',
            name='fellowship_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='researchscholar',
            name='graduation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
