# Generated by Django 2.2.7 on 2020-01-28 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('social_django', '0008_partial_timestamp'),
        ('authtoken', '0002_auto_20160226_1747'),
        ('research', '0004_auto_20200114_2017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResearchScholar',
        ),
    ]
