# Generated by Django 3.0.2 on 2020-02-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_researchscholar'),
        ('research', '0005_delete_researchscholar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='authors',
        ),
        migrations.AddField(
            model_name='project',
            name='faculty_authors',
            field=models.ManyToManyField(blank=True, related_name='project', to='users.Faculty'),
        ),
        migrations.AddField(
            model_name='project',
            name='scholar_authors',
            field=models.ManyToManyField(blank=True, related_name='project', to='users.ResearchScholar'),
        ),
        migrations.AddField(
            model_name='project',
            name='student_authors',
            field=models.ManyToManyField(blank=True, related_name='project', to='users.Student'),
        ),
        migrations.AddField(
            model_name='publication',
            name='faculty_authors',
            field=models.ManyToManyField(blank=True, related_name='publication', to='users.Faculty'),
        ),
        migrations.AddField(
            model_name='publication',
            name='scholar_authors',
            field=models.ManyToManyField(blank=True, related_name='publication', to='users.ResearchScholar'),
        ),
        migrations.AddField(
            model_name='publication',
            name='student_authors',
            field=models.ManyToManyField(blank=True, related_name='publication', to='users.Student'),
        ),
    ]
