# Generated by Django 3.0b1 on 2019-10-26 17:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='students', to=settings.AUTH_USER_MODEL)),
                ('id_num', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='ID Number')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='users.Department')),
            ],
            options={
                'verbose_name': 'student',
                'default_related_name': 'students',
            },
            bases=('users.customuser',),
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='faculties', to=settings.AUTH_USER_MODEL)),
                ('psrn', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='PSRN Number')),
                ('alt_email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='alternate email')),
                ('contact_num', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number is not in the correct format.', regex='^(((\\+?91)|0)[\\-\\s]?)?[6-9]\\d{9}$')])),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='users.Department')),
            ],
            options={
                'verbose_name': 'faculty',
                'default_related_name': 'faculties',
            },
            bases=('users.customuser',),
        ),
    ]
