# Generated by Django 3.0.2 on 2020-01-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191103_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='profile picture'),
        ),
    ]
