# Generated by Django 2.2.7 on 2020-01-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191103_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='alt_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='alternate email'),
        ),
    ]
