# Generated by Django 3.0.2 on 2020-01-14 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200114_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='alt_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='alternate email'),
        ),
    ]
